### ISSUE TITLE
please publish to npm

### ISSUE THREAD

**Issue by bcoe** [freebroccolo/atom-language-swift#9]
Could you please publish the swift module to npm? We are using the same highlighting engine as Atom now, and would love to add your grammar:

https://www.npmjs.com/package/polyglot-readme

**Comment by nostrademons** [comment]
Seconding this request, if at all possible.  [Atom's highlighting engine](https://www.npmjs.com/package/highlights) is available on npm, and is used by [marky-markdown](https://www.npmjs.com/package/marky-markdown) (the default markdown parser on NPM).  Publishing this to npm and getting it into marky-markdown would enable Swift support across all NPM README files, along with opening it up to anyone else using Markdown from Node.
